CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION postgis_tiger_geocoder;

-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id integer DEFAULT nextval('user_id_seq'::regclass) PRIMARY KEY,
    create_at time without time zone DEFAULT '02:49:51.806032'::time without time zone,
    update_at time without time zone DEFAULT '02:49:51.806032'::time without time zone,
    delete_at time without time zone DEFAULT '02:49:51.806032'::time without time zone,
    nick_name text DEFAULT '""'::text,
    user_name text DEFAULT '""'::text,
    age integer DEFAULT 0,
    pwd text DEFAULT '""'::text,
    email text DEFAULT '""'::text,
    gender integer DEFAULT 0,
    summary text DEFAULT '""'::text,
    phone text DEFAULT '""'::text,
    is_delete integer DEFAULT 0,
    openid text DEFAULT '""'::text,
    avatar_url text DEFAULT '""'::text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_pkey ON users(id int4_ops);



-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE temp (
    id SERIAL PRIMARY KEY,
    name text,
    age text,
    location point
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX temp_pkey ON temp(id int4_ops);

-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE session (
    id SERIAL PRIMARY KEY UNIQUE,
    session text,
    openid text UNIQUE,
    expire time without time zone,
    create_at time without time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX session_pkey ON session(id int4_ops);
CREATE UNIQUE INDEX session_id_key ON session(id int4_ops);
CREATE UNIQUE INDEX session_openid_key ON session(openid text_ops);


-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE msg (
    id SERIAL PRIMARY KEY
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX msg_pkey ON msg(id int4_ops);



-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE location (
    id SERIAL PRIMARY KEY,
    l_type integer,
    create_at text,
    update_at text,
    delete_at text,
    imgs text,
    location point,
    content text,
    user_id text,
    user_obj json,
    is_delete integer,
    viewed_num text,
    liked_num text,
    comment_num text,
    liked text,
    lat double precision,
    lng double precision
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX location_pkey ON location(id int4_ops);


-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE like (
    id SERIAL PRIMARY KEY
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX like_pkey ON like(id int4_ops);



-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE comments (
    id SERIAL PRIMARY KEY
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX comments_pkey ON comments(id int4_ops);
