go get -u "github.com/gin-gonic/gin"
go get -u "github.com/lib/pq"
go get -u "github.com/qiniu/api.v7/storage"
go get -u "github.com/qiniu/api.v7/auth/qbox"
go get -u "github.com/satori/go.uuid"
go get -u "github.com/twpayne/go-geom"
go get -u "github.com/twpayne/go-geom/encoding/ewkb"